name: announce

on:
  schedule:
    - cron: "30 14 * * *"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    container:
      image: tokkyo13/rogi_schedule:latest
      env:
        TOKEN: ${{ secrets.TOKEN }}
        GUILD_ID: ${{ secrets.GUILD_ID }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
    steps:
      - name: wait
        working-directory: /scripts
        run: bash sleep.sh
      - name: announce
        working-directory: /discordjs
        run: node index.js
