name: announce

on:
  schedule:
    - cron:  '*/5 * * * *'
    
jobs:
  docker:
    runs-on: ubuntu-latest
    container:
      image: tokkyo13/rogi_schedule:latest
    steps:
      - name: announce
        run: node index.js
